version: "3.1"

services:
  # node:
  #   image: node:8.10-alpine
  #   depends_on:
  #     - mongo
  #   working_dir: /usr/app
  #   volumes:
  #     - .:/usr/app
  #   command: '/bin/sh -c "yarn && yarn start"'

  mongo:
    image: mongo
    restart: always
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    entrypoint: "docker-entrypoint.sh --bind_ip 0.0.0.0"

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8089:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: example
